export const app = {
    id: "contry-quiz" as const,
    author: "Rushclin Takam" as const,
    description: "Formation Dev Challenge" as const,
    keywords: "#ecommerce #rushclin #takam" as const,
    themeColor: "#333e51" as const,
    supportedLngs: ["en", "fr"] as const,
    baseURL: "http://localhost:3000" as const,
    fullName: "Country quiz" as const,
  
    questionsList: [
      {
        id: 1,
        title: "1",
        question: "Quelle est la capitale du Cameroun ?",
        answers: [
          { title: "Douala" },
          { title: "Yaoundé" },
          { title: "Maroua" },
          { title: "Buéa" },
        ],
        country: "Cameroon",
      },
      {
        id: 2,
        title: "2",
        question: "Quelle est la capitale de la France ?",
        answers: [
          { title: "Paris" },
          { title: "Marseille" },
          { title: "Lyon" },
          { title: "Toulouse" },
        ],
        country: "France",
      },
      {
        id: 3,
        title: "3",
        question: "Quelle est la capitale des États-Unis ?",
        answers: [
          { title: "New York" },
          { title: "Washington, D.C." },
          { title: "Los Angeles" },
          { title: "Chicago" },
        ],
        country: "United States",
      },
      {
        id: 4,
        title: "4",
        question: "Quelle est la capitale de l'Allemagne ?",
        answers: [
          { title: "Berlin" },
          { title: "Munich" },
          { title: "Hambourg" },
          { title: "Francfort" },
        ],
        country: "Germany",
      },
      {
        id: 5,
        title: "5",
        question: "Quelle est la capitale du Japon ?",
        answers: [
          { title: "Tokyo" },
          { title: "Osaka" },
          { title: "Kyoto" },
          { title: "Hiroshima" },
        ],
        country: "Japan",
      },
      
      {
        id: 6,
        title: "6",
        question: "Quelle est la capitale du Brésil ?",
        answers: [
          { title: "Brasilia" },
          { title: "Rio de Janeiro" },
          { title: "São Paulo" },
          { title: "Belo Horizonte" },
        ],
        country: "Brazil",
      },
      {
        id: 7,
        title: "7",
        question: "Quelle est la capitale de l'Australie ?",
        answers: [
          { title: "Canberra" },
          { title: "Sydney" },
          { title: "Melbourne" },
          { title: "Brisbane" },
        ],
        country: "Australia",
      },
      {
        id: 8,
        title: "8",
        question: "Quelle est la capitale de l'Inde ?",
        answers: [
          { title: "New Delhi" },
          { title: "Mumbai" },
          { title: "Kolkata" },
          { title: "Chennai" },
        ],
        country: "India",
      },
      {
        id: 9,
        title: "9",
        question: "Quelle est la capitale de l'Espagne ?",
        answers: [
          { title: "Madrid" },
          { title: "Barcelone" },
          { title: "Valence" },
          { title: "Séville" },
        ],
        country: "Spain",
      },
      {
        id: 10,
        title: "10",
        question: "Quelle est la capitale du Canada ?",
        answers: [
          { title: "Ottawa" },
          { title: "Toronto" },
          { title: "Montréal" },
          { title: "Vancouver" },
        ],
        country: "Canada",
      },
    ] as const,
  };